### ISSUE TITLE
.h

### ISSUE THREAD

**Issue by rcomeau** [fivdi/pigpio#33]
pigpio.h missing

**Comment by fivdi** [comment]
Was there an error message displayed while installing the pigpio Node.js package saying that pigpio.h is missing? If so, it's probably because the pigpio C library is not installed. Newer versions of Raspbian Jessie come with the pigpio C library installed. Raspbian Jessie Lite and older versions of Raspbian don't come with the pigpio C library installed and the pigpio C library needs to be installed manually with the following commands:
```
sudo apt-get update
sudo apt-get install pigpio
```
If the pigpio C library is installed it should then be possible to install the pigpio Node.js package.

Further information can be found in the [Installation Section](https://github.com/fivdi/pigpio#installation) of the readme.

If this doesn't resolve the issue please provide further information about the error and how it can be reproduced.

**Comment by rcomeau** [comment]
I was working with two Raspberry Pis, and one somehow didn't get loaded with pigpio. My bad, all works fine when you load the C lib.
Rick Comeau


On Sunday, August 20, 2017, 6:29:43 AM EDT, Brian Cooke <notifications@github.com> wrote:


Was there an error message displayed while installing the pigpio Node.js package saying that pigpio.h is missing? If so, it's probably because the pigpio C library is not installed. Newer versions of Raspbian Jessie come with the pigpio C library installed. Raspbian Jessie Lite and older versions of Raspbian don't come with the pigpio C library installed and the pigpio C library needs to be installed manually with the following commands:
sudo apt-get update
sudo apt-get install pigpio

If the pigpio C library is installed it should then be possible to install the pigpio Node.js package.

Further information can be found in the Installation Section of the readme.

If this doesn't resolve the issue please provide further information about the error and how it can be reproduced.
