### ISSUE TITLE
Glitch filtering

### ISSUE THREAD

**Issue by marcinbudny** [fivdi/pigpio#44]
Is it possible to use the pigpio's [gpioGlitchFilter](http://abyz.me.uk/rpi/pigpio/cif.html#gpioGlitchFilter) with this library?

**Comment by fivdi** [comment]
Currently this isn't possible.

**Comment by fivdi** [comment]
It looks like it would be relatively easy to add.

**Comment by marcinbudny** [comment]
This is good news. Similar to glitch filtering is the [gpioNoiseFilter](http://abyz.me.uk/rpi/pigpio/cif.html#gpioNoiseFilter). 
Unfortunately I have no experience with native bindings in node, so I will have to catch up on that before attempting a PR.

**Comment by DvdBerg** [comment]
I also needed this feature, so I've decided to add it: #50

**Comment by fivdi** [comment]
@DvdBerg @marcinbudny pigpio@1.1.0 was just published on npm has a new [glitchFilter method](https://github.com/fivdi/pigpio/blob/master/doc/gpio.md#glitchfiltersteady).

@DvdBerg Thank you very much to taking the time to create the pull request.

**Comment by louisvangeldrop** [comment]
What about the gpioNoiseFilter? Using a RF433 receiver will cause thousands of noise interrupts per seconds killing the cpu of my Rasperry Pi.

**Comment by fivdi** [comment]
As mentioned above gpioNoiseFilter is supported. Please take a look at the documentation.

**Comment by louisvangeldrop** [comment]
Please point me to the document in https://github.com/fivdi/pigpio? I can't find it in the npm project

**Comment by fivdi** [comment]
Sorry, my mistake, the title of this issue is "Glitch Filtering" so I assumed you were asking about glitch filtering and now see that you are asking about noise filtering. gpioNoiseFilter isn't actually supported by this Node.js module at this time. Only [glitch filtering](https://github.com/fivdi/pigpio/blob/master/doc/gpio.md#glitchfiltersteady) is supported.

Please note that the documentation for the pigpio C library functions [gpioGlitchFilter](http://abyz.me.uk/rpi/pigpio/cif.html#gpioGlitchFilter) and [gpioNoiseFilter](http://abyz.me.uk/rpi/pigpio/cif.html#gpioNoiseFilter) state that calling these functions has no affects on interrupts. Calling them does however have affects on alerts.

**Comment by louisvangeldrop** [comment]
I am using the alert function.

**Comment by fivdi** [comment]
Would you like to create a PR for adding gpioNoiseFilter?

**Comment by louisvangeldrop** [comment]
No idea how to do that. I have no experience in C++ programming
