### ISSUE TITLE
MPC23017 example?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [fivdi/pigpio#51]
Are there any examples for using with a port expander like MPC23017?

**Comment by fivdi** [comment]
@GeoffreyPlitt The MCP23017 is an I2C device. Although the [pigpio C library](https://github.com/joan2937/pigpio) does have an I2C API, this I2C API is not available in the pigpio Node.js module. The main reason it's not available is because there was already the [i2c-bus](https://github.com/fivdi/i2c-bus) module which runs on multiple platforms and not only on the Raspberry Pi.

**Comment by GeoffreyPlitt** [comment]
gotcha, thanks!
